{% set name = "prefect-dask" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 54aab08668004a0bbf465a61f7481f5d6b8d57337ffb1fc246eeae7646ecf2b4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - distributed >=2022.2.0
    - prefect >=2.8.2
    - python >=3.7

test:
  imports:
    - prefect_dask
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PrefectHQ/prefect-dask
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Prefect integrations with the Dask execution framework.
  doc_url: https://prefecthq.github.io/prefect-dask/
  dev_url: https://github.com/PrefectHQ/prefect-dask

extra:
  recipe-maintainers:
    - madkinsz
    - desertaxle
    - ahuang11
