{% set name = "prefect-dask" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 325353e2858361524981e223f66a5b587173850474468f98ba63bf020dc785c9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - distributed >=2022.2.0
    - prefect >=2.8.2
    - python >={{ python_min }}

test:
  imports:
    - prefect_dask
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/PrefectHQ/prefect-dask
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Prefect integrations with the Dask execution framework.
  doc_url: https://prefecthq.github.io/prefect-dask/
  dev_url: https://github.com/PrefectHQ/prefect-dask

extra:
  recipe-maintainers:
    - madkinsz
    - desertaxle
    - ahuang11
