{% set name = "prefect-dask" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 54aab08668004a0bbf465a61f7481f5d6b8d57337ffb1fc246eeae7646ecf2b4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - distributed >=2022.2.0
    - prefect >=3.1.0
    - python >={{ python_min }}

test:
  imports:
    - prefect_dask
  requires:
    - pip
    - python {{ python_min }}
  commands:
    # Check that the version is correct
    - sh -c '[ "$(python -c 'import prefect_dask; print(prefect_dask.__version__);' = "{{ version }}") ]'

about:
  home: https://github.com/PrefectHQ/prefect-dask
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Prefect integrations with the Dask execution framework.
  doc_url: https://prefecthq.github.io/prefect-dask/
  dev_url: https://github.com/PrefectHQ/prefect-dask

extra:
  recipe-maintainers:
    - zzstoatzz
    - cicdw
    - desertaxle
