{% set name = "prefect-dask" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8c0f697e5d8660885c1bc31675dce7b153c3d60925293f339d3326ef25add3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - distributed >=2022.2.0
    - prefect >=2.8.2
    - python >=3.7

test:
  imports:
    - prefect_dask
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/PrefectHQ/prefect-dask
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Prefect integrations with the Dask execution framework.
  doc_url: https://prefecthq.github.io/prefect-dask/
  dev_url: https://github.com/PrefectHQ/prefect-dask

extra:
  recipe-maintainers:
    - madkinsz
    - desertaxle
    - ahuang11
